version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./output:/app/output
      - zig-cache:/root/.cache/zig
    environment:
      - NODE_ENV=development
      - DEBUG=*
      - PDF_ENGINE=/usr/local/bin/wkhtmltopdf.sh
      - TEMP_DIR=/app/tmp
    command: node test.js

volumes:
  zig-cache: