name: Test and Deploy

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # macOS ARM64 builds
          - os: macos-latest
            node: 18
            architecture: arm64
            runner: macos
          - os: macos-latest
            node: 20
            architecture: arm64
            runner: macos
          # macOS x64 builds
          - os: macos-latest
            node: 18
            architecture: x64
            runner: macos
          - os: macos-latest
            node: 20
            architecture: x64
            runner: macos
          # Linux x64 builds
          - os: ubuntu-latest
            node: 18
            architecture: x64
            runner: linux
          - os: ubuntu-latest
            node: 20
            architecture: x64
            runner: linux

    steps:
      - uses: actions/checkout@v4
      
      # Cache dependencies
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install system dependencies for macOS
      - name: Install macOS dependencies
        if: matrix.runner == 'macos'
        run: |
          brew install python@3.9
          brew link --force python@3.9
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.architecture }}
          cache: 'npm'
      
      # Install node-gyp globally
      - name: Install node-gyp
        run: npm install -g node-gyp@latest
      
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0

      # Build and Test
      - name: Build and Test
        run: |
          python3 -V
          npm ci
          npm run build
          npm test
        env:
          PYTHON: python3
          npm_config_node_gyp: $(which node-gyp)
          NODE_OPTIONS: --max-old-space-size=4096

      # Upload artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}-node${{ matrix.node }}-${{ matrix.architecture }}
          path: |
            build/
            zig-out/

  deploy:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}