name: Prebuild

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [18, 20]
        fail-fast: false
        
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          
      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
          
      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        run: |
          npm run test:unit || true
          npm run test:integration || true
          npm run test:coverage || true
          
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        if: success() || failure()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  prebuild:
    needs: test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [18, 20]
        fail-fast: false
        
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          
      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
          
      - name: Install dependencies
        run: npm install
        
      - name: Build prebuilds
        run: npm run prebuildify
        
      - name: Package prebuilds
        run: tar -czf prebuilds-${{ matrix.os }}-node${{ matrix.node }}.tar.gz prebuilds/
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: prebuilds-${{ matrix.os }}-node${{ matrix.node }}.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: prebuilds-${{ matrix.os }}-node${{ matrix.node }}
          path: prebuilds/

  publish:
    needs: [test, prebuild]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    timeout-minutes: 15
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm install
        
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}