name: Test and Deploy

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: [16, 18, 20]
        architecture: [x64, arm64]
        exclude:
          - os: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        if: matrix.architecture == 'arm64'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      
      - name: Set up Docker Buildx
        if: matrix.architecture == 'arm64'
        uses: docker/setup-buildx-action@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.architecture }}
      
      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
      
      - name: Build ARM64
        if: matrix.architecture == 'arm64'
        run: |
          docker buildx build --platform linux/arm64 \
            --build-arg NODE_VERSION=${{ matrix.node }} \
            -t tik-forge-builder .
          docker run --rm --platform linux/arm64 tik-forge-builder
      
      - name: Build x64
        if: matrix.architecture == 'x64'
        run: |
          npm install
          npm run build
      
      - name: Test
        run: npm test

  deploy:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Build Multi-arch
        run: |
          npm ci
          npm run build
      
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
            LICENSE
            README.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}