name: Test and Deploy

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # macOS ARM64 builds (เฉพาะ Node.js 18, 20)
          - os: macos-latest
            node: 18
            architecture: arm64
            runner: macos
          - os: macos-latest
            node: 20
            architecture: arm64
            runner: macos
          # macOS x64 builds
          - os: macos-latest
            node: 18
            architecture: x64
            runner: macos
          - os: macos-latest
            node: 20
            architecture: x64
            runner: macos
          # Linux x64 builds
          - os: ubuntu-latest
            node: 18
            architecture: x64
            runner: linux
          - os: ubuntu-latest
            node: 20
            architecture: x64
            runner: linux
    steps:
      - uses: actions/checkout@v2
      
      # Install system dependencies for macOS
      - name: Install macOS dependencies
        if: matrix.runner == 'macos'
        run: |
          brew install python@3.11
          brew link --force python@3.11
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.architecture }}
      
      # Install node-gyp globally
      - name: Install node-gyp
        run: npm install -g node-gyp@latest
      
      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0

      # Build and Test
      - name: Build and Test
        run: |
          python3 -V
          npm install
          npm run build
          npm test
        env:
          PYTHON: python3
          npm_config_node_gyp: $(which node-gyp)

  deploy:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}